import { Inter } from "next/font/google";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";

import "./globals.css";
// import { AntdRegistry } from "@ant-design/nextjs-registry";
import Topbar from "@/Components/Topbar";
import Header from "@/Components/Header";
import Theme from "@/Theme/themeConfig";
import { ConfigProvider } from "antd";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <ConfigProvider theme={Theme}>
          <Header />
          <div className="sub_container">
            <Topbar />
            <div className="children_div"> {children}</div>
          </div>
        </ConfigProvider>
      </body>
    </html>
  );
}
