import { Inter } from "next/font/google";
// import "antd/dist/antd.css";
import "./globals.css";
import Topbar from "@/Components/Topbar";
import Header from "@/Components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <Header />
        <div className="sub_container">
          <Topbar />
          {children}
        </div>
      </body>
    </html>
  );
}
